# Generated by Django 5.2.17 on 2026-09-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('project-small', 'Small Project'), ('project-big', 'Big Project')], default='project-small', max_length=20),
        ),
    ]
