# Generated by Django 5.2.17 on 2026-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_project_ended_at_remove_project_started_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
